// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/mistral-client/mistral (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/client.go github.com/thomas-marquis/mistral-client/mistral Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mistral "github.com/thomas-marquis/mistral-client/mistral"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ChatCompletion mocks base method.
func (m *MockClient) ChatCompletion(ctx context.Context, req *mistral.ChatCompletionRequest) (*mistral.ChatCompletionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCompletion", ctx, req)
	ret0, _ := ret[0].(*mistral.ChatCompletionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatCompletion indicates an expected call of ChatCompletion.
func (mr *MockClientMockRecorder) ChatCompletion(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCompletion", reflect.TypeOf((*MockClient)(nil).ChatCompletion), ctx, req)
}

// ChatCompletionStream mocks base method.
func (m *MockClient) ChatCompletionStream(ctx context.Context, req *mistral.ChatCompletionRequest) (<-chan *mistral.CompletionChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCompletionStream", ctx, req)
	ret0, _ := ret[0].(<-chan *mistral.CompletionChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatCompletionStream indicates an expected call of ChatCompletionStream.
func (mr *MockClientMockRecorder) ChatCompletionStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCompletionStream", reflect.TypeOf((*MockClient)(nil).ChatCompletionStream), ctx, req)
}

// Embeddings mocks base method.
func (m *MockClient) Embeddings(ctx context.Context, req *mistral.EmbeddingRequest) (*mistral.EmbeddingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embeddings", ctx, req)
	ret0, _ := ret[0].(*mistral.EmbeddingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embeddings indicates an expected call of Embeddings.
func (mr *MockClientMockRecorder) Embeddings(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embeddings", reflect.TypeOf((*MockClient)(nil).Embeddings), ctx, req)
}

// GetModel mocks base method.
func (m *MockClient) GetModel(ctx context.Context, modelId string) (*mistral.BaseModelCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel", ctx, modelId)
	ret0, _ := ret[0].(*mistral.BaseModelCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModel indicates an expected call of GetModel.
func (mr *MockClientMockRecorder) GetModel(ctx, modelId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockClient)(nil).GetModel), ctx, modelId)
}

// ListModels mocks base method.
func (m *MockClient) ListModels(ctx context.Context) ([]*mistral.BaseModelCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx)
	ret0, _ := ret[0].([]*mistral.BaseModelCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockClientMockRecorder) ListModels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockClient)(nil).ListModels), ctx)
}

// SearchModels mocks base method.
func (m *MockClient) SearchModels(ctx context.Context, capabilities *mistral.ModelCapabilities) ([]*mistral.BaseModelCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchModels", ctx, capabilities)
	ret0, _ := ret[0].([]*mistral.BaseModelCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchModels indicates an expected call of SearchModels.
func (mr *MockClientMockRecorder) SearchModels(ctx, capabilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchModels", reflect.TypeOf((*MockClient)(nil).SearchModels), ctx, capabilities)
}
