// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/mistral-client/mlflow (interfaces: PromptRegistry)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/prompt_registry.go github.com/thomas-marquis/mistral-client/mlflow PromptRegistry
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mlflow "github.com/thomas-marquis/mistral-client/mlflow"
	gomock "go.uber.org/mock/gomock"
)

// MockPromptRegistry is a mock of PromptRegistry interface.
type MockPromptRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockPromptRegistryMockRecorder
	isgomock struct{}
}

// MockPromptRegistryMockRecorder is the mock recorder for MockPromptRegistry.
type MockPromptRegistryMockRecorder struct {
	mock *MockPromptRegistry
}

// NewMockPromptRegistry creates a new mock instance.
func NewMockPromptRegistry(ctrl *gomock.Controller) *MockPromptRegistry {
	mock := &MockPromptRegistry{ctrl: ctrl}
	mock.recorder = &MockPromptRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptRegistry) EXPECT() *MockPromptRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPromptRegistry) Get(ctx context.Context, name string, version mlflow.Version, opts ...mlflow.PromptOption) (mlflow.Prompt, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, version}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(mlflow.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPromptRegistryMockRecorder) Get(ctx, name, version any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, version}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPromptRegistry)(nil).Get), varargs...)
}
